[package]

name = "syslog_ng_rust"
version = "0.0.1"
authors = ["tibi"]
build = "build.rs"

[lib]

name = "syslog_ng_rust"
crate-type = ["dylib"]

[dependencies]
libc = "*"

[build-dependencies]
pkg-config = "0.3.5"
