[package]
name = "actiondb-parser"
version = "0.2.0"
authors = ["Tibor Benke <tibor.benke@balabit.com>"]

[lib]
name = "actiondb_parser"

[dependencies]
log = "*"

[dependencies.actiondb]
version = "0.3.0"

[dependencies.syslog-ng-sys]
path = "../syslog-ng-sys/"
