[package]
name = "actiondb-parser"
version = "0.1.0"
authors = ["Tibor Benke <tibor.benke@balabit.com>"]

[lib]
name = "actiondb_parser"

[dependencies]
log = "*"
actiondb = "0.2.1"

[dependencies.syslog-ng-sys]
path = "../syslog-ng-sys/"
