[package]
name = "in-list-filter"
version = "0.1.0"
authors = ["Tibor Benke <ihrwein@gmail.com>"]

[lib]
name = "in_list_filter"

[dependencies]
log = "*"

[dependencies.syslog-ng-sys]
path = "../syslog-ng-sys/"
