language: rust
sudo: false
distro: trusty

env:
- PKG_CONFIG_PATH=$HOME/install/syslog-ng/lib/pkgconfig

addons:
  apt:
    packages:
    - cmake
    - time
    - pkg-config
    - flex
    - bison
    - xsltproc
    - docbook-xsl
    - libevtlog-dev
    - libnet1-dev
    - libglib2.0-dev
    - libssl-dev
    - libjson0-dev
    - libwrap0-dev
    - libpcre3-dev
    - libcap-dev
    - libesmtp-dev
    - libgeoip-dev
    - libhiredis-dev
    - openjdk-7-jdk
    - autoconf-archive
    - cmake
    - python3

# run builds for all the trains (and more)
matrix:
  include:
    - rust: stable

before_script:
  - cd ..
  - git clone https://github.com/balabit/syslog-ng.git
  - cd syslog-ng
  - ./autogen.sh
  - ./configure --with-ivykis=internal --prefix=$HOME/install/syslog-ng --disable-python
  - make -j install
  - cd ../syslog-ng-rust-modules
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/install/syslog-ng ..
script:
  - make install
