language: python
sudo: false

python: "3.4"

env:
  global:
    - PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/install/syslog-ng/lib/pkgconfig
    - CMAKE_C_FLAGS=-std=gnu99
    - LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/install/syslog-ng/lib"
    - PATH="$HOME/.local/bin:$PATH"
  matrix:
#    - RUST_CHANNEL=nightly TEST_MODE=everything TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
    - RUST_CHANNEL=stable TEST_MODE=everything
#    - RUST_CHANNEL=beta TEST_MODE=everything

matrix:
  include:
    - env: RUST_CHANNEL=stable TEST_MODE=cmake

git:
  submodules: false

dist: trusty
cache:
  - pip

addons:
  apt:
    sources:
    - kubuntu-backports
    packages:
    - bison
    - flex
    - libcap-dev
    - libevtlog-dev
    - libglib2.0-dev
    - libjson0-dev
    - libwrap0-dev
    - pkg-config
    - cmake
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev

install:
  - pip install 'travis-cargo<0.2'
  - . .travis/rust-cpython-upgrade-hack.sh
  - .travis/install-ivykis.sh
  - .travis/install-syslog-ng.sh

script:
  - .travis/test-${TEST_MODE}.sh
