[package]
name = "correlation"
version = "0.2.0"
authors = ["Tibor Benke <ihrwein@gmail.com>"]

[[bin]]
name = "test"
path = "src/bin/test.rs"

[dependencies]
maplit = "0.1"
uuid = "0.1"
serde = "0.6"
serde_json = "0.6"
handlebars = "0.10"
rustc-serialize = "0.3"
log = "0.3"
env_logger = "0.3.1"

