[package]
name = "syslog-ng-rust-modules"
version = "0.1.0"
authors = ["Tibor Benke <ihrwein@gmail.com>"]

[lib]
name = "syslog_ng_rust_modules"
crate-type = ["dylib"]

[dependencies]
log = "*"

[dependencies.dummy-parser]
path = "dummy-parser"

[dependencies.actiondb-parser]
path = "actiondb-parser"

[dependencies.dummy-filter]
path = "dummy-filter"

[dependencies.in-list-filter]
path = "in-list-filter"

[dependencies.syslog-ng-sys]
path = "syslog-ng-sys"
