[package]
name = "actiondb-parser"
version = "0.2.0"
authors = ["Tibor Benke <tibor.benke@balabit.com>"]
build = "build.rs"

[lib]
crate_type = ["dylib"]

[dependencies]
log = "*"

[dependencies.actiondb]
version = "0.4.0"

[dependencies.syslog-ng-common]
git = "https://github.com/ihrwein/syslog-ng-rs.git"

[build-dependencies.syslog-ng-build]
git = "https://github.com/ihrwein/syslog-ng-rs.git"
