[package]
name = "python-parser"
version = "0.1.0"
authors = ["Tibor Benke <ihrwein@gmail.com>"]
build = "build.rs"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
syslog-ng-common = {version = "0.6", path= "../syslog-ng-rs/syslog-ng-common"}
cpython = {version = "0.0.5", path = "../rust-cpython"}
log = "0.3"
env_logger = "0.3"

[build-dependencies]
syslog-ng-build = "0.2"
