[package]

name = "syslog-ng-rust-modules"
version = "0.1.0"
authors = ["Tibor Benke <ihrwein@gmail.com>"]

[lib]
name = "syslog_ng_rust_modules"
crate-type = ["dylib"]

[dependencies.dummy_filter]
path = "dummy_filter"

[dependencies.in_list_filter]
path = "in_list_filter"

[dependencies.syslog-ng-sys]
path = "syslog-ng-sys"
