[package]
name = "actiondb-parser"
version = "0.2.0"
authors = ["Tibor Benke <tibor.benke@balabit.com>"]
build = "build.rs"
license = "MIT/Apache-2.0"

[lib]
crate_type = ["dylib"]

[dependencies]
log = "0.3"
actiondb = "0.6.0"
syslog-ng-common = "0.4.0"

[build-dependencies]
syslog-ng-build = "0.2"
