[package]
name = "actiondb-parser"
version = "0.2.0"
authors = ["Tibor Benke <tibor.benke@balabit.com>"]
build = "build.rs"

[lib]
crate_type = ["dylib"]

[dependencies]
log = "*"

[dependencies.actiondb]
version = "0.4.0"
path = "../actiondb"

[dependencies.syslog-ng-common]
path = "../syslog-ng-rs/syslog-ng-common"

[build-dependencies.syslog-ng-build]
path = "../syslog-ng-rs/syslog-ng-build"
