[package]
name = "actiondb-parser"
version = "0.2.4"
authors = ["Tibor Benke <tibor.benke@balabit.com>"]
build = "build.rs"
homepage = "https://github.com/ihrwein/actiondb-parser"
repository = "https://github.com/ihrwein/actiondb-parser"
readme = "README.md"
keywords = ["log", "parser"]
description = "A parser module for syslog-ng based on ActionDB"
license = "MIT/Apache-2.0"

[lib]
crate_type = ["rlib", "dylib"]

[dependencies]
log = "0.3"
actiondb = "^0.6.1"
syslog-ng-common = "0.7"

[build-dependencies]
syslog-ng-build = "0.2"
