[package]
name = "actiondb"
version = "0.2.1"
authors = ["Tibor Benke <tibor.benke@balabit.com>"]

[[bin]]
name = "adbtool"
path = "src/bin/adbtool.rs"

[dependencies]
clap = "1.0"
log = "0.3"
uuid = "0.1"
serde = "0.4"
