[package]
name = "syslog-ng-sys"
version = "0.0.1"
authors = ["tibi"]
build = "build.rs"
links = "syslog-ng"

[lib]
name = "syslog_ng_sys"
crate-type = ["dylib"]

[dependencies]
libc = "*"

[build-dependencies]
pkg-config = "0.3.5"
