[package]
name = "syslog-ng-sys"
version = "0.2.0"
authors = ["tibi"]
build = "build.rs"
links = "syslog-ng"

[lib]
name = "syslog_ng_sys"

[dependencies]
libc = "0.2"
log = "0.3"

[build-dependencies]
pkg-config = "0.3"
