[package]
name = "syslog-ng-common"
version = "0.4.0"
authors = ["Tibor Benke <ihrwein@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
log = "0.3"

[dependencies.syslog-ng-sys]
syslog-ng-sys = "0.2"
